[package]
name = "axolotlsay-js"
description = "JavaScript port of axolotlsay"
version = "0.9.0"
license = "MIT"
repository = "https://github.com/axodotdev/axolotlsay-hybrid"
binaries = ["axolotlsay-js"]
build-command = ["bash", "build.sh"]
